### ISSUE TITLE
Rep / member are being used interchangebly

### ISSUE THREAD

**Issue by OLI9292** [bencbernstein/Track-Your-Reps#22]
let's pick one and stick to it

**Comment by bencbernstein** [comment]
even though it connotes house reps, let's use 'reps' since 'members' seems vague

**Comment by OLI9292** [comment]
👍 
gotcha I was gonna go with members because reps is so short, but that isn't really a good reason anyway

also reps matches the app's name

i'll try a search replace all and see if things don't break

**Comment by bencbernstein** [comment]
yeah cool. i think 'track your reps' is ok for now, but i think we can do better. i bet we'll get inspired when we see the events coming in and see what it's doing for us personally

**Comment by OLI9292** [comment]
lets leave this issue open

**Comment by bencbernstein** [comment]
I propose standardizing everything:

Member used instead of rep or member
Action or Event? I think Action
Clean up XCode Folder Structure to Make Easier

**Comment by OLI9292** [comment]
lets go with member.  I did a search find & replace for "rep" and "member" and it would be v. difficult to switch "member" for "rep" at this point - it shows up in a ton in our saved json for example. also, I think it makes more sense since it's a nickname for the CongressMember model

**Comment by OLI9292** [comment]
I'm gonna jam on this tonight, so I'll look to do those things

**Comment by OLI9292** [comment]
I like Action over Event

**Comment by bencbernstein** [comment]
sounds good.

i think actions are actually on events from data. so probably we keep them as discrete identifiers. we should change 'recent decisions' to 'recent actions'
