### ISSUE TITLE
Change red / blue colors for yes /no

### ISSUE THREAD

**Issue by OLI9292** [bencbernstein/Track-Your-Reps#49]

**Comment by bencbernstein** [comment]
![thumb up-104](https://cloud.githubusercontent.com/assets/13627407/23858239/2b58d76a-07d6-11e7-9831-40d0d907cac0.png)
![thumbs down-104](https://cloud.githubusercontent.com/assets/13627407/23858240/2b625312-07d6-11e7-9e64-bc7c2cbd3bb2.png)
