### ISSUE TITLE
Extend gray line to screen width

### ISSUE THREAD

**Issue by OLI9292** [bencbernstein/Track-Your-Reps#54]
![screen shot 2017-03-13 at 11 47 04 pm](https://cloud.githubusercontent.com/assets/13812317/23885088/72109d84-0847-11e7-8a76-9cffe422f9d4.png)

**Comment by bencbernstein** [comment]
i was just looking at that. actually suggest we make it pink and make the other lines like this. adds a little bit of nice asymmetry + is apple human interface practice

**Comment by OLI9292** [comment]
totes.  that's what we mocked up in figma anyway
